name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install root dependencies
        run: npm ci

      - name: Install Gulp CLI globally
        run: npm install --global gulp-cli

      - name: Run Gulp build
        run: gulp build

      - name: Install Cloud Function dependencies
        run: |
          cd functions
          npm ci

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ env.GOOGLE_GHA_CREDS_PATH }}" >> $GITHUB_ENV

      - name: Set Firebase function secrets
        if: github.event_name == 'push'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_GHA_CREDS_PATH }}
        run: |
          npm install -g firebase-tools
          firebase functions:secrets:set METOFFICE_API_URL \
            --project fb-paragliding-db \
            --value "${{ secrets.METOFFICE_API_URL }}"
          firebase functions:secrets:set PURETRACK_API_KEY \
            --project fb-paragliding-db \
            --value "${{ secrets.PURETRACK_API_KEY }}"
          firebase functions:secrets:set PURETRACK_BEARER_TOKEN \
            --project fb-paragliding-db \
            --value "${{ secrets.PURETRACK_BEARER_TOKEN }}"
          firebase functions:secrets:set TELEGRAM_API_KEY \
            --project fb-paragliding-db \
            --value "${{ secrets.TELEGRAM_API_KEY }}"
          firebase functions:secrets:set UK_TIDAL_API \
            --project fb-paragliding-db \
            --value "${{ secrets.UK_TIDAL_API }}"

      - name: Deploy to Firebase Hosting and Functions
        if: github.event_name == 'push'
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting,functions --project fb-paragliding-db
