name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Gulp CLI globally
        run: npm install --global gulp-cli

      - name: Run Gulp build
        run: gulp build

      - name: Write service account key to file
        run: echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json

      - name: Deploy to Firebase Hosting and Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting,functions

      - name: Clean up key file
        run: rm $HOME/gcp-key.json
