name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install root dependencies
        run: npm ci

      - name: Install Gulp CLI globally
        run: npm install --global gulp-cli

      - name: Run Gulp build
        run: npm run build

      - name: Install Cloud Function dependencies
        run: |
          cd functions
          npm ci
          cd ..

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set/Update All Firebase Secrets from GitHub
        env:
          # This maps your GitHub secrets to environment variables.
          # Ensure you have created secrets in your GitHub repo's settings with these exact names.
          METOFFICE_API_URL: ${{ secrets.METOFFICE_API_URL }}
          PURETRACK_API_KEY: ${{ secrets.PURETRACK_API_KEY }}
          PURETRACK_BEARER_TOKEN: ${{ secrets.PURETRACK_BEARER_TOKEN }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          UK_TIDAL_API: ${{ secrets.UK_TIDAL_API }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          npm install -g firebase-tools
          echo "Setting secrets in Google Secret Manager from GitHub Secrets..."

          # Each command pipes the value from the corresponding environment variable
          # into the Firebase CLI, creating a new version of the secret in Google Cloud.
          echo "$METOFFICE_API_URL" | firebase functions:secrets:set METOFFICE_API_URL --project fb-paragliding-db
          echo "$PURETRACK_API_KEY" | firebase functions:secrets:set PURETRACK_API_KEY --project fb-paragliding-db
          echo "$PURETRACK_BEARER_TOKEN" | firebase functions:secrets:set PURETRACK_BEARER_TOKEN --project fb-paragliding-db
          echo "$TELEGRAM_API_KEY" | firebase functions:secrets:set TELEGRAM_API_KEY --project fb-paragliding-db
          echo "$UK_TIDAL_API" | firebase functions:secrets:set UK_TIDAL_API --project fb-paragliding-db
          echo "$MY_SECRET" | firebase functions:secrets:set MY_SECRET --project fb-paragliding-db
          
          echo "All secrets have been set."

      - name: Deploy to Firebase Hosting and Functions
        if: github.event_name == 'push'
        run: |
          # The deploy command will bind the functions to the 'latest' version of the secrets.
          # Since the previous step just created new 'latest' versions, this works perfectly.
          firebase deploy --only hosting,functions --project fb-paragliding-db --token "${{ secrets.FIREBASE_TOKEN }}"